name: GitPush • ignite

on:
  workflow_dispatch:
  push:
    branches: [ main ]

concurrency:
  group: gitpush-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITPUSH_APP_NAME: "ignite"
      GITPUSH_SPLASH: "true"
    steps:
      - uses: actions/checkout@v4

      